baseURL = "https://hungry-lalande-72070e.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Sayan's Website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
#    tag = "tags"

[outputs]
  home = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[params]
title = "I'm Sayan Basak"
author = "Sayan Basak"
copyright = "2020-{{ YEAR }}"
description = "Call me Sayan"
profilePicture = "images/SAYAN_BASAK.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
# customCss = []
# example ["js/custom.js"]
# customJs = [] 
mainSections = ["post", "docs"]
images = ["images/SAYAN_BASAK.png"]
doNotLoadAnimations = true # Animations are loaded by default
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
postSectionName = "blog"
contentratio = 0.75
rssFullContent = true


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@example.com"


[languages]
[en]
LanguageName = "EN"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[menu.footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"

[Languages]
  [Languages.en]
  title = "My blog"
  weight = 1
  LanguageName = "EN"